name: Build

on:
  push:
    branches:
      - master
    tags: 
      - v*.*.*

jobs:
  build:
    
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
      fail-fast: false
    
    runs-on: windows-latest
    
    env:
      InnoSetupScriptFilePath: SpecifiedRecordsExporter.iss
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
        
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }} --self-contained true --no-restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
      - name: Create installer
        if: matrix.configuration == 'Release'
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "${{ env.InnoSetupScriptFilePath }}"
        shell: cmd
        
      - name: Upload artifacts
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v2
        with:
          name: Setup
          path: 'Output\*-setup.exe'
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: matrix.configuration == 'Release' && startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: 'Output\*-setup.exe'
          fail_on_unmatched_files: true
        
